"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TwoNumberStatsProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MEAN_FIELD_NUMBER: int
    STDDEV_FIELD_NUMBER: int
    COUNT_FIELD_NUMBER: int
    mean: float = ...
    stddev: float = ...
    count: int = ...

    def __init__(
        self,
        *,
        mean: typing.Optional[float] = ...,
        stddev: typing.Optional[float] = ...,
        count: typing.Optional[int] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "count", b"count", "mean", b"mean", "stddev", b"stddev"
        ],
    ) -> bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "count", b"count", "mean", b"mean", "stddev", b"stddev"
        ],
    ) -> None: ...

global___TwoNumberStatsProto = TwoNumberStatsProto

class BlobProfile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: int
    BYTES_USED_FIELD_NUMBER: int
    name: typing.Text = ...

    @property
    def bytes_used(self) -> global___TwoNumberStatsProto: ...
    def __init__(
        self,
        *,
        name: typing.Optional[typing.Text] = ...,
        bytes_used: typing.Optional[global___TwoNumberStatsProto] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "bytes_used", b"bytes_used", "name", b"name"
        ],
    ) -> bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "bytes_used", b"bytes_used", "name", b"name"
        ],
    ) -> None: ...

global___BlobProfile = BlobProfile

class ProfDAGProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: int
    MEAN_FIELD_NUMBER: int
    STDDEV_FIELD_NUMBER: int
    EXECUTION_TIME_FIELD_NUMBER: int
    OUTPUT_PROFILE_FIELD_NUMBER: int
    EXTRA_INFO_FIELD_NUMBER: int
    name: typing.Text = ...
    mean: float = ...
    stddev: float = ...
    extra_info: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...

    @property
    def execution_time(self) -> global___TwoNumberStatsProto: ...
    @property
    def output_profile(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___BlobProfile
    ]: ...
    def __init__(
        self,
        *,
        name: typing.Optional[typing.Text] = ...,
        mean: typing.Optional[float] = ...,
        stddev: typing.Optional[float] = ...,
        execution_time: typing.Optional[global___TwoNumberStatsProto] = ...,
        output_profile: typing.Optional[typing.Iterable[global___BlobProfile]] = ...,
        extra_info: typing.Optional[typing.Iterable[typing.Text]] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "execution_time",
            b"execution_time",
            "mean",
            b"mean",
            "name",
            b"name",
            "stddev",
            b"stddev",
        ],
    ) -> bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "execution_time",
            b"execution_time",
            "extra_info",
            b"extra_info",
            "mean",
            b"mean",
            "name",
            b"name",
            "output_profile",
            b"output_profile",
            "stddev",
            b"stddev",
        ],
    ) -> None: ...

global___ProfDAGProto = ProfDAGProto

class ProfDAGProtos(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATS_FIELD_NUMBER: int
    NET_NAME_FIELD_NUMBER: int
    OPS_STATS_FIELD_NUMBER: int
    net_name: typing.Text = ...

    @property
    def stats(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___ProfDAGProto
    ]: ...
    @property
    def ops_stats(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___OpProfile
    ]: ...
    def __init__(
        self,
        *,
        stats: typing.Optional[typing.Iterable[global___ProfDAGProto]] = ...,
        net_name: typing.Optional[typing.Text] = ...,
        ops_stats: typing.Optional[typing.Iterable[global___OpProfile]] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["net_name", b"net_name"]
    ) -> bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "net_name", b"net_name", "ops_stats", b"ops_stats", "stats", b"stats"
        ],
    ) -> None: ...

global___ProfDAGProtos = ProfDAGProtos

class OpProfile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    IDX_FIELD_NUMBER: int
    NET_NAME_FIELD_NUMBER: int
    TYPE_FIELD_NUMBER: int
    EXEC_TIME_SECS_FIELD_NUMBER: int
    idx: typing.Text = ...
    net_name: typing.Text = ...
    type: typing.Text = ...
    exec_time_secs: float = ...

    def __init__(
        self,
        *,
        idx: typing.Optional[typing.Text] = ...,
        net_name: typing.Optional[typing.Text] = ...,
        type: typing.Optional[typing.Text] = ...,
        exec_time_secs: typing.Optional[float] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "exec_time_secs",
            b"exec_time_secs",
            "idx",
            b"idx",
            "net_name",
            b"net_name",
            "type",
            b"type",
        ],
    ) -> bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "exec_time_secs",
            b"exec_time_secs",
            "idx",
            b"idx",
            "net_name",
            b"net_name",
            "type",
            b"type",
        ],
    ) -> None: ...

global___OpProfile = OpProfile
