name: formatting-black

on: [push, pull_request]

jobs:
  black:
    runs-on: self-hosted
    steps:
      # Uncomment this step when github-worker-1 gets into an error state related to submodules 
      # - name: Nuke the worker
      #   run: rm -rf $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      # black 19.10 is only compatible with certain versions of click: https://github.com/psf/black/issues/2964
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install black-compatible click
        run: pip install click==8.0.4
      - name: Install black
        run: pip install black==22.10.0
      - name: Check black formatting
        run: black --check --config $GITHUB_WORKSPACE/pyproject.toml $GITHUB_WORKSPACE
