name: Testing

on: 
  workflow_run:
    workflows: [formatting-black]
    types:
      - completed

jobs:
  
  pytest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install testing dependencies
        run: |
          pip install pytest
          pip install expecttest
      - name: Do testing
        id: do_test_1
        run: pytest test/test_bundled_inputs.py test/test_comparison_utils.py
  
  another-py-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install testing dependencies
        run: |
          pip install pytest
          pip install expecttest
      - name: Do testing
        id: do_test_2
        run: pytest test/profiler
